name: Update playlists

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install needed libraries
        run: pip install spotipy requests

      - name: Decode and save GH secrets
        env:
          SPOTIPY_CACHE: ${{ secrets.SPOTIPY_CACHE }}
        run: python decodesecrets.py

      - name: Run "Most listened to" script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: 'http://localhost:8000/callback'
        run: python create_100inmonth.py
      - name: Run "200 latest liked" script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: 'http://localhost:8000/callback'
        run: python create_200liked.py

      - name: Update GH secrets
        env:
          SPOTIPY_CACHE: ${{ secrets.SPOTIPY_CACHE }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python updatesecrets.py
